@baseUrl = https://localhost:7126

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "TestPassword123!"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "TestPassword123!"
}

### Refresh
POST {{baseUrl}}/api/auth/refresh

### Logout
POST {{baseUrl}}/api/auth/logout